# Exercise 5.A NumPy Fundamentals

This exercise practices NumPy arrays, dimensions, data types, transposing, indexing, slicing, and creating 3-D arrays.

In [1]:
import numpy as np

## Array Basics

In [2]:
fruits = ["apple", "banana", "cherry", "date"]
arr_1 = np.array(fruits)

print(arr_1)
print(arr_1.dtype)

# The dtype returned is usually <U6.
# U means Unicode string.
# 6 means the longest string has 6 characters.
arr_2 = np.array([[10, 11, 12], [13, 14, 15]])

print(arr_2)

['apple' 'banana' 'cherry' 'date']
<U6
[[10 11 12]
 [13 14 15]]


In [3]:
print(arr_2.T)
print(arr_2)

# No, arr_2.T does not permanently change arr_2.
# It only shows a transposed view/output.
arr_3 = np.array([[1, 3, 5], [2, 4, 6]])

print(arr_3)
arr_4 = np.array([arr_3[0, 2], arr_3[1, 1]])

print(arr_4)
arr_5 = np.ones((2, 2, 2))

print(arr_5)


[[10 13]
 [11 14]
 [12 15]]
[[10 11 12]
 [13 14 15]]
[[1 3 5]
 [2 4 6]]
[5 4]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
