# Exercise 1.B NumPy Random


In [1]:
import numpy as np

## Generating Random Numbers

In [2]:
r_1 = np.random.randint(1, 21, size=2)
print(r_1)

[9 6]


In [4]:
r_2 = np.random.randint(1, 21, size=(1, 2))
print(r_2)

[[ 6 12]]


In [3]:
r_3 = np.random.rand(2, 1)
print(r_3)

[[0.00910578]
 [0.25843869]]


In [5]:
r_4 = np.random.randint(20, 101, size=(4, 5))
print(r_4)

[[80 80 79 63 94]
 [50 79 34 39 30]
 [97 86 64 27 76]
 [79 98 78 74 56]]


In [6]:
r_5 = np.random.rand(4, 5)
print(r_5)

[[0.03970857 0.51190942 0.5556445  0.11360028 0.08720018]
 [0.22319123 0.12623851 0.05498959 0.44967351 0.79250511]
 [0.6886751  0.56358426 0.79525505 0.89865378 0.93064932]
 [0.86784574 0.99329114 0.12142775 0.4109101  0.56270732]]


## Generating Random Choices from an Array

In [7]:
students = np.array([
    "Hana", "Sara", "Maya", "John",
    "David", "Amina", "Kevin", "Lily",
    "Sam", "Noah", "Grace", "Daniel"
])
print(students)

['Hana' 'Sara' 'Maya' 'John' 'David' 'Amina' 'Kevin' 'Lily' 'Sam' 'Noah'
 'Grace' 'Daniel']


In [8]:
call_on = np.random.choice(students)
print(call_on)

Maya


In [9]:
breakout_groups = np.random.choice(students, size=(3, 4))
print(breakout_groups)

# This may not be the best way to assign breakout groups because students can repeat.
# Some students might appear more than once, and some might not be chosen at all.

[['Maya' 'David' 'Grace' 'Grace']
 ['John' 'Kevin' 'Amina' 'Sara']
 ['Grace' 'Sam' 'Sam' 'Hana']]


In [10]:
call_on_weighted = np.random.choice(
    students,
    size=5,
    p=[0.30, 0.10, 0.10, 0.10, 0.10, 0.10, 0.05, 0.05, 0.05, 0.05, 0.00, 0.00]
)

print(call_on_weighted)

# Hana has a 30% chance of being selected.
# Grace and Daniel have 0% chance of being selected.
# The other students have smaller probability values.
# All p values add up to 1.00.

['Hana' 'David' 'Hana' 'John' 'Hana']


## Generating a Normal Distribution

In [11]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bell_curve)

[[13.29687272  5.69218917 18.77304778  4.30591825  7.71195863]
 [12.66077771 14.60377378 17.90976527  8.72637252  6.30019964]
 [17.70800367 14.98665323 11.37415771  4.18166103 14.55761154]
 [ 7.37260619 10.6120978   6.95100354 13.26242532 13.29734081]]
