In [2]:
import numpy as np

## Sample Arrays

In [3]:
r_1 = np.random.randint(1, 21, size=2)
r_2 = np.random.randint(1, 21, size=(1, 2))
r_3 = np.random.rand(2, 1)
r_4 = np.random.randint(20, 101, size=(4, 5))
r_5 = np.random.rand(4, 5)

print(r_1)
print(r_2)
print(r_3)
print(r_4)
print(r_5)

[11 12]
[[ 2 19]]
[[0.59716773]
 [0.34048417]]
[[76 39 80 29 42]
 [42 25 71 48 21]
 [95 95 63 36 29]
 [40 48 91 34 76]]
[[0.63089178 0.53480824 0.87722396 0.85770592 0.70878723]
 [0.46085469 0.52688368 0.38470804 0.3644588  0.74492169]
 [0.73228643 0.72472579 0.9382876  0.29957253 0.85062656]
 [0.24877303 0.01081812 0.41227719 0.74495698 0.21903274]]


## Permutations

In [4]:
print(r_4)

[[76 39 80 29 42]
 [42 25 71 48 21]
 [95 95 63 36 29]
 [40 48 91 34 76]]


In [5]:
np.random.shuffle(r_4)
print(r_4)

[[95 95 63 36 29]
 [40 48 91 34 76]
 [42 25 71 48 21]
 [76 39 80 29 42]]


The shuffle changed the order of the rows in r_4. It changed the original array directly.

## Mathematical Operations

In [6]:
print(r_1)
print(r_1.shape)

print(r_2)
print(r_2.shape)

result = np.add(r_1, r_2)
print(result)
print(result.shape)

[11 12]
(2,)
[[ 2 19]]
(1, 2)
[[13 31]]
(1, 2)


In [7]:
print(r_1)
print(r_1.shape)

print(r_3)
print(r_3.shape)

result = np.add(r_1, r_3)
print(result)
print(result.shape)

[11 12]
(2,)
[[0.59716773]
 [0.34048417]]
(2, 1)
[[11.59716773 12.59716773]
 [11.34048417 12.34048417]]
(2, 2)


In [8]:
print(r_2)
print(r_2.shape)

print(r_4)
print(r_4.shape)

result = np.add(r_2, r_4)
print(result)
print(result.shape)

[[ 2 19]]
(1, 2)
[[95 95 63 36 29]
 [40 48 91 34 76]
 [42 25 71 48 21]
 [76 39 80 29 42]]
(4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [9]:
# r_1 + r_4 gives an error because the shapes do not match for broadcasting.
# r_2 + r_4 works because r_2 has 1 row and 2 columns only if the columns match.
# Since r_4 has 5 columns, r_2 + r_4 gives an error.
# r_3 + r_4 gives an error because r_3 has 2 rows and 1 column, but r_4 has 4 rows and 5 columns.

print(np.add(r_1, r_4))

ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

In [10]:
print(np.add(np.array([1]), r_4))

[[96 96 64 37 30]
 [41 49 92 35 77]
 [43 26 72 49 22]
 [77 40 81 30 43]]


In [11]:
print(np.add(np.array([[1]]), r_4))

[[96 96 64 37 30]
 [41 49 92 35 77]
 [43 26 72 49 22]
 [77 40 81 30 43]]


In [12]:
print(np.add(np.array([1, 1, 1, 1, 1]), r_4))

[[96 96 64 37 30]
 [41 49 92 35 77]
 [43 26 72 49 22]
 [77 40 81 30 43]]


In [13]:
# This gives an error because [[1], [1]] has 2 rows,
# but r_4 has 4 rows. The shapes cannot broadcast together.

print(np.add(np.array([[1], [1]]), r_4))

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

Broadcasting lets NumPy combine arrays with different shapes when the smaller array can fit across the bigger array. The add function adds matching values together. If one array has only one value, that value can be added to every value in the larger array. The shape of the final result usually follows the larger array.

## Rounding

In [14]:
print(r_3)

[[0.59716773]
 [0.34048417]]


In [15]:
print(np.trunc(r_3))

[[0.]
 [0.]]


In [16]:
print(np.fix(r_3))

[[0.]
 [0.]]


In [17]:
print(np.floor(r_3))

[[0.]
 [0.]]


In [18]:
print(np.round(r_3, 2))

[[0.6 ]
 [0.34]]


In [19]:
## Cumulative Operations

In [20]:
print(r_4)
print(np.sum(r_4))
print(np.sum(r_4, axis=0))
print(np.sum(r_4, axis=1))
print(np.cumsum(r_4))
print(np.cumsum(r_4, axis=0))

[[95 95 63 36 29]
 [40 48 91 34 76]
 [42 25 71 48 21]
 [76 39 80 29 42]]
1080
[253 207 305 147 168]
[318 289 207 266]
[  95  190  253  289  318  358  406  497  531  607  649  674  745  793
  814  890  929 1009 1038 1080]
[[ 95  95  63  36  29]
 [135 143 154  70 105]
 [177 168 225 118 126]
 [253 207 305 147 168]]


## Grocery Problem

In [21]:
# Order: vegetables, fruits, snacks, beverages

bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])

print(bag1)
print(bag2)
bag1_total = np.sum(bag1)
bag2_total = np.sum(bag2)

print(f"The first bag contains {bag1_total} items, and the second bag contains {bag2_total} items.")

[2 3 4 0]
[4 0 1 2]
The first bag contains 9 items, and the second bag contains 7 items.


In [22]:
category_totals = np.add(bag1, bag2)

print(f"There are {category_totals[0]} vegetables, {category_totals[1]} fruits, {category_totals[2]} boxes of snacks, and {category_totals[3]} beverages in the two grocery bags.")

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


## Teamwork

In [23]:
ali = np.array([5, 4, 6, 4, 2])
ben = np.array([0, 5, 5, 3, 4])
carla = np.array([3, 6, 0, 3, 4])
all_knocks = np.array([ali, ben, carla])
print(all_knocks)
person_totals = np.sum(all_knocks, axis=1)
group_total = np.sum(all_knocks)

print(f"Ali knocked on {person_totals[0]} doors.")
print(f"Ben knocked on {person_totals[1]} doors.")
print(f"Carla knocked on {person_totals[2]} doors.")
print(f"The group knocked on {group_total} doors total.")
daily_totals = np.sum(all_knocks, axis=0)
rolling_total = np.cumsum(daily_totals)
estimated_votes = rolling_total * 0.5

print(estimated_votes)

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]
Ali knocked on 21 doors.
Ben knocked on 17 doors.
Carla knocked on 16 doors.
The group knocked on 54 doors total.
[ 4.  11.5 17.  22.  27. ]
